### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by anelson0828** [grace-shopper-1906/grace-shopper#1]
### Products
- [ ] Title  - string
- [ ] Category - enum, strings - required (must belong to at least 1)
- [ ] Picture - string (image url)
- [ ] Description - text
- [ ] Price - float
- [ ] Inventory Quantity - number

### Review
- [ ] Author - userId (only logged in users can write reviews)
- [ ] Product - prodcts.id 
- [ ] Star - number between 1-5
- [ ] Text - text (not empty, at least 30 characters, optional?)

### Users
-in boilermaker (email, password, googleId, salt)
- [ ] Admin - enum, true/false
- [ ] Shipping address - string
- [ ] First name - string
- [ ] Last name - string

### Order/Product Association Table
- [ ] Order ID
- [ ] Product ID
- [ ] Product quantity
- [ ] Product Price

### Orders
- [ ] User ID [OPTIONAL (can be null) ]
- [ ] Session ID [REQUIRED]
- [ ] Date ordered
- [ ] Status - enum: inCart, Created, Processing, Cancelled, Completed
- [ ] Total price - float (implemented by hook before create - sum product prices)

### Categories 
- [ ] Name

### Session
- [ ] session id
- [ ] expires
- [ ] Data object - stores cart info

### Relationships
- [ ] Product has many Reviews
- [ ] Review belongs to Product
- [ ] Orders belongs to User
- [ ] Orders have many Products
- [ ] Product has many Orders
- [ ] User has many Orders
- [ ] User has many Reviews
- [ ] Reviews belongs to User
- [ ] Product has many Categories
- [ ] Categories belong to many products (Done w/ through table)

**Comment by anelson0828** [comment]
Questions 

- [ ] do we want to store carts differently for logged in vs not logged in users?

**Comment by anelson0828** [comment]
would be cool to see cart if not logged in, and close browser

product ID, cart ID, user ID

save cart ID on session data

**Comment by amayaea** [comment]
Just realized we need to address quantity in the shopping cart as well

**Comment by anelson0828** [comment]
true and in orders - I updated above

**Comment by anelson0828** [comment]
I think we should maybe add a table for categories - admin can create category options but otherwise we want them to be a select item

**Comment by anelson0828** [comment]
https://dbdiagram.io/d/5d3fa5ddced98361d6dd1e43

**Comment by anelson0828** [comment]
database query as a group 
set status to created and check inventory quantity  minus order quantity greater or equal to 0
if anything in the clause fails, then they all fail 

order status - use instance method, add updated at, updated by
inventory_quantity - have all quantity ever minus all quantity though orders

Sequelize has way to do transactions
could setup middleware that interacts with sequelize and for lifecycle of this request run all work in same transaction 

shipping address table
